@URL = https://web-production-8ee60.up.railway.app

# Para probar en local: http://127.0.0.1:5000


#######################################
# USUARIO (tabla Usuario)

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Christian",
    "email": "christian.ramos@example.com",
    "contrasenia": "123456",
    "edad": 18
}

###
# Actualizar el nombre del usuario con id=1
PUT {{URL}}/actualizar_usuario/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario/1


#######################################
# PROYECTO

###
# Crear dieta
POST {{URL}}/nuevo_recetas
Content-Type: application/json

{
    "dieta": 1,
    "nombre": "pollo con arroz",
    "descripcion": "pechuga de pollo con arroz, rico y facil",
    "carbohidrato": "arroz",
    "proteina": "pechuga de pollo",
    "condicion": "diabeticos"
}

###
# Obtener dietas
GET {{URL}}/traer_recetas

###
# Guardar registro de glucosa
POST {{URL}}/registro_glucosa
Content-Type: application/json

{
    "glucosa": 95,
    "fecha": "28-9-2026 15:38",
    "nota": "Despues del almuerzo",
    "comentarios": "me gusta las pasas",
    "Usuario_id": 1
}

###
# Obtener registros de glucosa
GET {{URL}}/registro_glucosa